### ISSUE TITLE
Some Squad dlls seem to have snuck in the new build.

### ISSUE THREAD

**Issue by Rodhern** [magico13/Modlets#1]
As the title says, in EditorTime, I see Assembly-CSharp, UnityEngine and UnityEngine.UI dlls.

**Comment by magico13** [comment]
Should be fixed now. I was pulling out all the .dlls in the "bin" directory and should have been grabbing it from the "obj" directory. The build process of the modlets is a bit of a pain since I wanted it to be expandable (or retractable if I remove any) without having to hardcode a bunch of stuff. Because of that it's had a lot of hiccups.
