### ISSUE TITLE
Who is right?

### ISSUE THREAD

**Issue by Reknot** [magico13/Modlets#2]
Hey there. 
Been mucking about with NIMBY for the past hour or so, seems to work good. 
Wish we had a part to attack to update the Beacons location every now and then. Would be awesome to have a rescue fleet for recovery. 
However, I also use Waypoint Manager to get a general sense of distance and saw this just now(see attached picture)
![whosright](https://user-images.githubusercontent.com/11231726/29030762-66340d30-7b8c-11e7-91c2-e9dc9d10a549.png)
;

Waypoint manager says 353km
NIMBY says 306km

Now this is a small issue, would just be cool to have them match?

Thank you for your work! 
Take care!
// Daniel

**Comment by magico13** [comment]
How was the waypoint set up? 50km is a pretty big discrepancy... NIMBY uses the latitude and longitude that KSP provides for the KSC. You can check the Beacons.cfg file to see what longitude and latitude it's using. If you can post the contents of that file here I'm curious if the waypoint and the beacon are at different lon/lat. If not, then that's concerning since NIMBY is just doing a "great circle distance", which is the distance along the surface of a sphere.

And crap, I might have accidentally used a longitude instead of a latitude in that calculation. Let me double check that.

**Comment by magico13** [comment]
Try this build and let me know if they line up better: http://magico13.net:8080/job/Modlets/lastSuccessfulBuild/artifact/NIMBY.zip

**Comment by Reknot** [comment]
Straight up Kappa-Pasta the waypoint from the Beacons.CFG. 
It's as accurate as the config file. 

New files works 100%. It's just as accurate as Waypoint manager. 
Thanks for quick fix! 
Here's Proof
![whosright](https://user-images.githubusercontent.com/11231726/29034108-7888b3d6-7b97-11e7-8711-2519a218326d.png)

Wonderful! 
Thanks a bunch! Will be a interesting play-trough.
NIMBY, and pressure limits on things. So, they need to be Boyent enough to stay afloat in the sea or they will get crushed. Else, aim for land. Will require accurate entry planning. And off course, no quickload or revert. 
Owh boy.

**Comment by magico13** [comment]
Sounds like it'll be a challenge! I'll close this issue once I update the official download, until then feel free to keep using the build you're on.

**Comment by magico13** [comment]
The official download was updated last night and also added a mobile recovery beacon option. The Mobile Recovery Beacon requires Module Manager, a science lab, and an engineer onboard. I may alter those requirements in the future since the science lab is a bit far down the tech tree.
