### ISSUE TITLE
Zero padding for Dated Quicksaves

### ISSUE THREAD

**Issue by charlesstaats** [magico13/Modlets#6]
Feature request: Please add zero padding for Dated Quicksaves so that when the quicksaves are placed in alphabetical order, they will automatically be in temporal order too.

**Comment by magico13** [comment]
Note that the modlets are no longer being maintained in this repo but instead are here: https://github.com/linuxgurugamer/Magico13_Modlets

As of this code at least (not sure if it has changed at all in that repo) you can zero pad the date by changing the template in the config file to use [year0], [day0], [minute0], etc instead of [year], [day], [minute].

**Comment by charlesstaats** [comment]
Thanks! It seems to be working. I've filed [an issue](https://github.com/linuxgurugamer/Magico13_Modlets/issues/4) at the new location.
